// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkApi.Models;

#nullable disable

namespace ParkApi.Migrations
{
    [DbContext(typeof(ParkApiContext))]
    [Migration("20230609163248_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine.",
                            ParkName = "Acadia",
                            State = "Maine"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "Arches National Park is a national park in eastern Utah, United States. The park is adjacent to the Colorado River, 4 miles north of Moab, Utah. More than 2,000 natural sandstone arches are located in the park, including the well-known Delicate Arch, as well as a variety of unique geological resources and formations.",
                            ParkName = "Arches",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "Badlands National Park is an American national park located in southwestern South Dakota. The park protects 242,756 acres of sharply eroded buttes and pinnacles, along with the largest undisturbed mixed grass prairie in the United States.",
                            ParkName = "Badlands",
                            State = "South Dakota"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "Big Bend National Park is an American national park located in West Texas, bordering Mexico. The park has national significance as the largest protected area of Chihuahuan Desert topography and ecology in the United States.",
                            ParkName = "Big Bend",
                            State = "Texas"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "Biscayne National Park is an American national park in southern Florida, south of Miami. The park preserves Biscayne Bay and its offshore barrier reefs. Ninety-five percent of the park is water, and the shore of the bay is the location of an extensive mangrove forest.",
                            ParkName = "Biscayne",
                            State = "Florida"
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "Black Canyon of the Gunnison National Park is an American national park located in western Colorado and managed by the National Park Service. There are two primary entrances to the park: the south rim entrance is located 15 miles east of Montrose, while the north rim entrance is 11 miles south of Crawford and is closed in the winter.",
                            ParkName = "Black Canyon of the Gunnison",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 7,
                            Description = "Bryce Canyon National Park is an American national park located in southwestern Utah. The major feature of the park is Bryce Canyon, which despite its name, is not a canyon, but a collection of giant natural amphitheaters along the eastern side of the Paunsaugunt Plateau.",
                            ParkName = "Bryce Canyon",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 8,
                            Description = "Canyonlands National Park is an American national park located in southeastern Utah near the town of Moab. The park preserves a colorful landscape eroded into countless canyons, mesas, and buttes by the Colorado River, the Green River, and their respective tributaries.",
                            ParkName = "Canyonlands",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 9,
                            Description = "Capitol Reef National Park is an American national park located in south-central Utah. The park is approximately 60 miles long on its north–south axis but an average of just 6 miles wide. The park was established in 1971 to preserve 241,904 acres of desert landscape and is open all year with May through September being the highest visitation months.",
                            ParkName = "Capitol Reef",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 10,
                            Description = "Carlsbad Caverns National Park is an American national park in the Guadalupe Mountains of southeastern New Mexico. The primary attraction of the park is the show cave, Carlsbad Cavern. Carlsbad Caverns National Park is open every day of the year except Thanksgiving, Christmas, and New Year's Day.",
                            ParkName = "Carlsbad Caverns",
                            State = "New Mexico"
                        },
                        new
                        {
                            ParkId = 11,
                            Description = "Channel Islands National Park is an American national park that consists of five of the eight Channel Islands off the coast of the U.S. state of California, in the Pacific Ocean. Although the islands are close to the shore of densely populated Southern California, their isolation has left them relatively undeveloped.",
                            ParkName = "Channel Islands",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 12,
                            Description = "Congaree National Park is an American national park in central South Carolina. The park preserves the largest tract of old growth bottomland hardwood forest left in the United States. The lush trees growing in this floodplain forest are some of the tallest in the Eastern U.S., forming one of the highest temperate deciduous forest canopies remaining in the world.",
                            ParkName = "Congaree",
                            State = "South Carolina"
                        },
                        new
                        {
                            ParkId = 13,
                            Description = "Crater Lake National Park is an American national park located in southern Oregon. Established in 1902, Crater Lake is the fifth-oldest national park in the United States and the only national park in Oregon. The park encompasses the caldera of Crater Lake, a remnant of a destroyed volcano, Mount Mazama, and the surrounding hills and forests.",
                            ParkName = "Crater Lake",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 14,
                            Description = "Cuyahoga Valley National Park is an American national park that preserves and reclaims the rural landscape along the Cuyahoga River between Akron and Cleveland in Northeast Ohio. The 32,572-acre park is administered by the National Park Service, but within its boundaries are areas independently managed as county parks or as public or private businesses.",
                            ParkName = "Cuyahoga Valley",
                            State = "Ohio"
                        },
                        new
                        {
                            ParkId = 15,
                            Description = "Death Valley National Park is an American national park that straddles the California–Nevada border, east of the Sierra Nevada. The park boundaries include Death Valley, the northern section of Panamint Valley, the southern section of Eureka Valley, and most of Saline Valley.",
                            ParkName = "Death Valley",
                            State = "California"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
